---
title: "Project"
author: "Sony kiran"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(ISLR)
library(caret)
library(dplyr)
library(cluster)
library(factoextra)
library(NbClust)
library(ppclust)
library(dendextend)
library(tidyverse)
library(ggplot2)
library(proxy)
library(stats)
library("tidyr")
library(useful)
library(rpart)
library(rpart.plot)
setwd("C:/Users/devar/Documents/FML/Project")
data<- read.csv("projectfile.csv")
#using  head to get first few rows of the data set
#head(data)
#using str to analyse the structure of the data set
str(data)
# using summary to analyse the summary of the data set
summary(data)
nrow(data)
```

```{r}
#Now I am scaling the data to remove  NA values from the data set
# Here I am Removing NA values from data set using omit function
data1 <- na.omit(data)
nrow(data1)
```

```{r}
#Now I'm taking 2 percent of data
data2<-data1 %>% sample_frac(0.2)
nrow(data2)
view(data2)
```

```{r}
#Now I'm Changing Char variables to Numeric
chars <- sapply(data2, is.character)
data2[ , chars] <- as.data.frame(apply(data2[ , chars], 2, as.numeric))
sapply(data2, class)
view(data2)
nrow(data2)

```

#Datapartition
```{r}
set.seed(6543)
data3 <- sample(c(TRUE, FALSE), nrow(data2), replace=TRUE, prob=c(0.75,0.25))

Train = data2[data3,]

Test = data2[!data3,]
View(Train)
nrow(Train)

```

```{r}
set.seed(6543)
Train1 <- Train[,c('fuel_cost_per_mmbtu','fuel_mmbtu_per_unit','fuel_received_units')]
Train1 <- scale(Train1)
```

```{r}
set.seed(6543)
fviz_nbclust(Train1, kmeans, method = "silhouette")
fviz_nbclust(Train1, kmeans, method = "wss")
#fviz_dist(distance)
k1<- kmeans(Train1, centers = 1)
k2<- kmeans(Train1, centers = 2)
k3<- kmeans(Train1, centers = 3)
k4<- kmeans(Train1, centers = 4)
k4$centers
k4$size
k4$cluster[100]
fviz_cluster(k1, data = Train1)
print(k3)
fviz_cluster(k2, data = Train1)
fviz_cluster(k3, data = Train1)
fviz_cluster(k4, data = Train1)
```

```{r}
#Hierarchial Clustering
clustdata <- dist(Train1, method = "euclidean")
clustdata1 <- hclust(clustdata, method = "complete")
plot(clustdata1, cex=0.9,hang=-8)
rect.hclust(clustdata1, k=3, border = 1:20)
library(useful)
plot(k4, data = Train1 )
##plot(k4, data = Train1, class="Cultivar")
clusplot(Train1,k4$cluster, main="Clusters",color = TRUE, labels = 3,lines = 0)
#fviz_cluster(k4,data=Train1)
```

```{r}
#DB-Scan Clustering
dbscan::kNNdistplot(Train1,k=3)
db=fpc::dbscan(Train1,eps= 0.9,MinPts = 10)
fviz_cluster(db,Train1, stand= FALSE, frame=FALSE,goem= "point")
```







